### ISSUE TITLE
Is it possible to do the Python wrapping with VTK 9 

### ISSUE THREAD

**Issue by 1939938853** [zippy84/vtkbool#50]
Is it possible to do the vtkbool Python wrapping with VTK 9?

Thanks

**Comment by zippy84** [comment]
The new module system is available in the refactoring branch. But be aware, the branch is still under development.

**Comment by whophil** [comment]
For what it's worth, the `refactoring` branch, currently at [a5593b7](https://github.com/zippy84/vtkbool/commit/a5593b74dc44e356ca9a0a01484921329fa7ae92), works fine for me with VTK 9.1.0, but does not build with VTK 9.0.1.

**Comment by zippy84** [comment]
@whophil Could you please show me the output of the failed build.

**Comment by whophil** [comment]
@zippy84 here is the failing output when using VTK 9.0.1.

<details>

```
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found Python3: $PREFIX/bin/python3.10 (found suitable version "3.10.4", minimum required is "3.10") found components: Interpreter Development.Module Development.Embed
-- Found ZLIB: $PREFIX/lib/libz.dylib (found version "1.2.12")
-- Found EXPAT: $PREFIX/lib/libexpat.dylib (found version "2.4.8")
-- Found double-conversion: $PREFIX/lib/libdouble-conversion.dylib
-- Found LZ4: $PREFIX/lib/liblz4.dylib (found version "1.9.3")
-- Found LZMA: $PREFIX/lib/liblzma.dylib (found version "5.2.5")
-- Found utf8cpp: $PREFIX/include
-- Found Eigen3: $PREFIX/include/eigen3 (found version "3.4.0")
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Configuring done
-- Generating done
-- Build files have been written to: $SRC_DIR/build
[  5%] Generating the wrap hierarchy for vtkBool
[ 11%] Building CXX object module/CMakeFiles/vtkBool.dir/__/vtkPolyDataBooleanFilter.o
[ 17%] Building CXX object module/CMakeFiles/vtkBool.dir/__/vtkPolyDataContactFilter.o
[ 23%] Building CXX object module/CMakeFiles/vtkBool.dir/__/Utilities.o
[ 23%] Built target vtkBool-hierarchy
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataContactFilter.cxx:290:55: warning: implicit conversion loses integer precision: 'vtkIdType' (aka 'long long') to 'int' [-Wshorten-64-to-32]
            vtkTriangleStrip::DecomposeStrip(cellItr->GetNumberOfPoints(), ptIds->GetPointer(0), cells);
            ~~~~~~~~~~~~~~~~                 ~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataContactFilter.cxx:297:54: warning: implicit conversion loses integer precision: 'vtkIdType' (aka 'long long') to 'int' [-Wshorten-64-to-32]
                    pd->InsertNextCell(VTK_TRIANGLE, n, pts);
                        ~~~~~~~~~~~~~~               ^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:418:33: warning: implicit conversion changes signedness: 'vtkIdType' (aka 'long long') to 'std::vector<long long>::size_type' (aka 'unsigned long') [-Wsign-conversion]
                    indA = poly[i]; // * hier
                           ~~~~ ^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:419:33: warning: implicit conversion changes signedness: 'vtkIdType' (aka 'long long') to 'std::vector<long long>::size_type' (aka 'unsigned long') [-Wsign-conversion]
                    indB = poly[j]; // * hier
                           ~~~~ ^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:511:56: warning: operand of ? changes signedness: 'long long' to 'std::vector<long long>::size_type' (aka 'unsigned long') [-Wsign-conversion]
                sp.edge[1] = poly[i+1 == numPts ? 0 : i+1]; // * hier
                             ~~~~                     ~^~
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:695:49: warning: implicit conversion changes signedness: 'std::size_t' (aka 'unsigned long') to 'std::__deque_iterator<long long, long long *, long long &, long long **, long, 512>::difference_type' (aka 'long') [-Wsign-conversion]
                    _lines.erase(_lines.begin()+i); // * hier
                                               ~^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:700:49: warning: implicit conversion changes signedness: 'std::size_t' (aka 'unsigned long') to 'std::__deque_iterator<long long, long long *, long long &, long long **, long, 512>::difference_type' (aka 'long') [-Wsign-conversion]
                    _lines.erase(_lines.begin()+i); // * hier
                                               ~^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:705:49: warning: implicit conversion changes signedness: 'std::size_t' (aka 'unsigned long') to 'std::__deque_iterator<long long, long long *, long long &, long long **, long, 512>::difference_type' (aka 'long') [-Wsign-conversion]
                    _lines.erase(_lines.begin()+i); // * hier
                                               ~^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:710:49: warning: implicit conversion changes signedness: 'std::size_t' (aka 'unsigned long') to 'std::__deque_iterator<long long, long long *, long long &, long long **, long, 512>::difference_type' (aka 'long') [-Wsign-conversion]
                    _lines.erase(_lines.begin()+i); // * hier
                                               ~^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:1068:54: warning: implicit conversion changes signedness: 'const vtkIdType' (aka 'const long long') to 'std::vector<std::deque<StripPtR>>::size_type' (aka 'unsigned long') [-Wsign-conversion]
                        StripType &stripA = strips[a.strip], // * hier
                                            ~~~~~~ ~~^~~~~
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:1069:48: warning: implicit conversion changes signedness: 'const vtkIdType' (aka 'const long long') to 'std::vector<std::deque<StripPtR>>::size_type' (aka 'unsigned long') [-Wsign-conversion]
                            &stripB = strips[b.strip]; // * hier
                                      ~~~~~~ ~~^~~~~
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:1135:53: warning: implicit conversion changes signedness: 'const vtkIdType' (aka 'const long long') to 'std::vector<std::deque<StripPtR>>::size_type' (aka 'unsigned long') [-Wsign-conversion]
                        StripType &strip = strips[a.strip]; // * hier
                                           ~~~~~~ ~~^~~~~
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:1523:34: warning: implicit conversion changes signedness: 'std::size_t' (aka 'unsigned long') to 'vtkIdType' (aka 'long long') [-Wsign-conversion]
            cell->SetNumberOfIds(num); // * hier
                  ~~~~~~~~~~~~~~ ^~~
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:1832:84: warning: unused parameter 'conts' [-Wunused-parameter]
void vtkPolyDataBooleanFilter::AddAdjacentPoints (vtkPolyData *pd, vtkIdTypeArray *conts, PolyStripsType &polyStrips) {
                                                                                   ^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:1985:80: warning: implicit conversion loses integer precision: 'vtkIdType' (aka 'long long') to 'int' [-Wshorten-64-to-32]
                                pd->InsertNextLinkedCell(VTK_POLYGON, newPoly->GetNumberOfIds(), newPoly->GetPointer(0));
                                    ~~~~~~~~~~~~~~~~~~~~              ~~~~~~~~~^~~~~~~~~~~~~~~~
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:2634:42: warning: implicit conversion loses integer precision: 'const long long' to 'int' [-Wshorten-64-to-32]
            cfA->AddSpecifiedRegion(itr->first);
                 ~~~~~~~~~~~~~~~~~~ ~~~~~^~~~~
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:2640:42: warning: implicit conversion loses integer precision: 'const long long' to 'int' [-Wshorten-64-to-32]
            cfB->AddSpecifiedRegion(itr->first);
                 ~~~~~~~~~~~~~~~~~~ ~~~~~^~~~~
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:2649:41: warning: implicit conversion loses integer precision: 'vtkIdType' (aka 'long long') to 'int' [-Wshorten-64-to-32]
                cfA->AddSpecifiedRegion(i);
                     ~~~~~~~~~~~~~~~~~~ ^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:2657:41: warning: implicit conversion loses integer precision: 'vtkIdType' (aka 'long long') to 'int' [-Wshorten-64-to-32]
                cfB->AddSpecifiedRegion(i);
                     ~~~~~~~~~~~~~~~~~~ ^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:2856:58: warning: implicit conversion changes signedness: 'decltype(__x.base() - __y.base())' (aka 'long') to 'std::vector<unsigned long>::value_type' (aka 'unsigned long') [-Wsign-conversion]
                groups[itrB-polys.begin()].push_back(itrA-polys.begin()); // * hier
                                           ~~~~~~~~~ ~~~~^~~~~~~~~~~~~~
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:2856:28: warning: implicit conversion changes signedness: 'decltype(__x.base() - __y.base())' (aka 'long') to 'std::vector<std::vector<unsigned long>>::size_type' (aka 'unsigned long') [-Wsign-conversion]
                groups[itrB-polys.begin()].push_back(itrA-polys.begin()); // * hier
                ~~~~~~ ~~~~^~~~~~~~~~~~~~
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/vtkPolyDataBooleanFilter.cxx:3100:37: warning: implicit conversion changes signedness: 'unsigned long' to 'const std::map<long long, Prio>::key_type' (aka 'const long long') [-Wsign-conversion]
                if (polyPrios.count(src) == 1) { // * hier
                              ~~~~~ ^~~
2 warnings generated.
20 warnings generated.
[ 29%] Linking CXX shared library ../lib/libvtkBool.dylib
[ 29%] Built target vtkBool
[ 35%] Generating Python wrapper sources for vtkBoolModule
[ 41%] Generating the Python module initialization sources for vtkBoolPython
[ 47%] Generating Python wrapper sources for vtkPolyDataContactFilter
[ 52%] Generating Python wrapper sources for vtkPolyDataBooleanFilter
[ 58%] Building CXX object CMakeFiles/test_merger.dir/testing/test_merger.o
Scanning dependencies of target vtkBoolPython
[ 64%] Building CXX object CMakeFiles/vtkBoolPython.dir/CMakeFiles/vtkBoolPython/vtkPolyDataBooleanFilterPython.o
[ 70%] Building CXX object CMakeFiles/vtkBoolPython.dir/CMakeFiles/vtkBoolPython/vtkBoolModulePython.o
[ 76%] Building CXX object CMakeFiles/vtkBoolPython.dir/CMakeFiles/vtkBoolPython/vtkPolyDataContactFilterPython.o
[ 82%] Building CXX object CMakeFiles/vtkBoolPython.dir/CMakeFiles/vtkBoolPythonPython/vtkBoolPythonInitImpl.o
[ 88%] Building CXX object CMakeFiles/vtkBoolPython.dir/CMakeFiles/vtkBoolPythonPython/vtkBoolPythonInit.o
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/testing/test_merger.cxx:75:12: error: member access into incomplete type 'vtkIdTypeArray'
    cellIds->SetName("OrigCellIds");
           ^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include/vtk-9.0/vtkAbstractArray.h:67:7: note: forward declaration of 'vtkIdTypeArray'
class vtkIdTypeArray;
      ^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/testing/test_merger.cxx:76:12: error: member access into incomplete type 'vtkIdTypeArray'
    cellIds->InsertNextValue(0);
           ^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include/vtk-9.0/vtkAbstractArray.h:67:7: note: forward declaration of 'vtkIdTypeArray'
class vtkIdTypeArray;
      ^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/testing/test_merger.cxx:77:35: error: no viable conversion from 'vtkSmartPointer<vtkIdTypeArray>' to 'vtkDataArray *'
    pd->GetCellData()->SetScalars(cellIds);
                                  ^~~~~~~
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include/vtk-9.0/vtkSmartPointer.h:188:3: note: candidate function
  operator T*() const noexcept { return static_cast<T*>(this->Object); }
  ^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include/vtk-9.0/vtkDataSetAttributes.h:150:32: note: passing argument to parameter 'da' here
  int SetScalars(vtkDataArray* da);
                               ^
In file included from /Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/testing/test_merger.cxx:17:
In file included from /Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include/vtk-9.0/vtkCellData.h:30:
In file included from /Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include/vtk-9.0/vtkDataSetAttributes.h:48:
In file included from /Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include/vtk-9.0/vtkDataSetAttributesFieldList.h:59:
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include/vtk-9.0/vtkSmartPointer.h:218:63: error: incomplete type 'vtkIdTypeArray' named in nested name specifier
  static vtkSmartPointer<T> New() { return vtkSmartPointer<T>(T::New(), NoReference()); }
                                                              ^~~
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/testing/test_merger.cxx:74:80: note: in instantiation of member function 'vtkSmartPointer<vtkIdTypeArray>::New' requested here
    vtkSmartPointer<vtkIdTypeArray> cellIds = vtkSmartPointer<vtkIdTypeArray>::New();
                                                                               ^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include/vtk-9.0/vtkAbstractArray.h:67:7: note: forward declaration of 'vtkIdTypeArray'
class vtkIdTypeArray;
      ^
In file included from /Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/testing/test_merger.cxx:17:
In file included from /Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include/vtk-9.0/vtkCellData.h:30:
In file included from /Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include/vtk-9.0/vtkDataSetAttributes.h:48:
In file included from /Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include/vtk-9.0/vtkDataSetAttributesFieldList.h:59:
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include/vtk-9.0/vtkSmartPointer.h:199:43: error: static_cast from 'vtkObjectBase *' to 'vtkIdTypeArray *', which are not related by inheritance, is not allowed
  T* operator->() const noexcept { return static_cast<T*>(this->Object); }
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/work/testing/test_merger.cxx:75:12: note: in instantiation of member function 'vtkSmartPointer<vtkIdTypeArray>::operator->' requested here
    cellIds->SetName("OrigCellIds");
           ^
/Users/philchiu/miniconda3/conda-bld/vtkbool_1654443293774/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/include/vtk-9.0/vtkAbstractArray.h:67:7: note: 'vtkIdTypeArray' is incomplete
class vtkIdTypeArray;
      ^
5 errors generated.
make[2]: *** [CMakeFiles/test_merger.dir/testing/test_merger.o] Error 1
make[1]: *** [CMakeFiles/test_merger.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 94%] Linking CXX shared module lib/python3.10/site-packages/vtkbool/vtkBool.so
[ 94%] Built target vtkBoolPython
make: *** [all] Error 2
```
</details>

**Comment by whophil** [comment]
Thanks @zippy84 ! Can confirm this builds with VTK 9.01 and VTK 9.1.0
